Repository Gloss-y/Glossy_Matcha, pull requests merged in 2025-08, with the labels that each got.

#52 feat: 웹폰트 추가(프리텐다드, 열린명조)
  fe/src/styles/variables.scss
Labels: enhancement, FE_issue

#51 [FE] variables.scss 생성
  fe/src/styles/variables.scss
Labels: FE_issue, init

#53 [FE]웹폰트 파일 위치 수정
  fe/src/styles/fonts.scss
  fe/src/styles/variables.scss
Labels: FE_issue

#58 [FE] components 폴더 추가, 변수 이름 변경, next-intl 라이브러리 설치, 로고 이미지 추가
  fe/package-lock.json
  fe/package.json
  fe/src/components/Header/Header.tsx
  fe/src/public/images/logo/logo-1.png
  fe/src/public/images/logo/logo-c-b.png
  fe/src/styles/variables.scss
Labels: FE_issue, fix

#61 [BE] feat: Django ORM Model, Django Templates Model develop
  be/glossymatcha/migrations/0001_initial.py
  be/glossymatcha/migrations/0002_dailysales_yearlysales_remove_sales_offline_sales_and_more.py
  be/glossymatcha/migrations/0002_remove_products_is_active_remove_products_is_export_and_more.py
  be/glossymatcha/migrations/0003_alter_suppliers_email_alter_suppliers_phone.py
  be/glossymatcha/models.py
Labels: enhancement, BE_issue, fix

#62 [BE] feat: settings.py edit
  be/glossy/settings.py
Labels: enhancement, BE_issue

#65 Be/feature/models
  be/glossymatcha/migrations/0004_inquiries_message_en_productimages_alt_text_en_and_more.py
  be/glossymatcha/models.py
Labels: feature, BE_issue

#66 [FE] feat: footer 수정, nav 테스트 완료
  fe/src/components/Footer/Footer.module.scss
  fe/src/components/Footer/Footer.tsx
  fe/src/components/Nav/Nav.tsx
Labels: feature, FE_issue, fix

#68 [BE] feat: admin에서 인라인으로 데이터 관리
  be/glossymatcha/admin.py
Labels: feature, BE_issue

#72 [BE] feat: Create ProductsImagesAdmin class kr/en version
  be/glossymatcha/admin.py
Labels: feature, BE_issue

#77 [BE] feat: Edit ProductSpecificationsAdmin class kr/en version
  be/glossymatcha/admin.py
Labels: feature, BE_issue

#79 [BE] feat: Create InquirySerializer class kr/en version
  be/glossymatcha/serializers.py
Labels: feature, BE_issue

#80 [BE] feat: Create ProductImageSerializer class kr/en version
  be/glossymatcha/serializers.py
Labels: feature, BE_issue

#82 [BE] feat: Create ProductSpecificationSerializer class kr/en version
  be/glossymatcha/serializers.py
Labels: feature, BE_issue

#83 [BE] feat: Create ProductSerializer class kr/en version
  be/glossymatcha/serializers.py
Labels: feature, BE_issue

#85 [BE] feat: Create ProductListSerializer class kr/en version
  be/glossymatcha/serializers.py
Labels: feature, BE_issue

#86 [FE] feat: 브랜드 소개 페이지 pc 디자인 구현
  fe/src/app/about/page.module.scss
  fe/src/app/about/page.tsx
  fe/src/components/About/BrandHistory.module.scss
  fe/src/components/About/BrandHistory.tsx
  fe/src/components/About/BrandIntro.module.scss
  fe/src/components/About/BrandIntro.tsx
  fe/src/components/About/BrandPhilosophy.module.scss
  fe/src/components/About/BrandPhilosophy.tsx
  fe/src/components/About/JejuMatcha.module.scss
  fe/src/components/About/JejuMatcha.tsx
Labels: feature, FE_issue

#89 [FE] fix: font 설정 수정
  fe/src/styles/fonts.scss
  fe/src/styles/mixins.scss
Labels: FE_issue, fix

#90 [BE] fix: model fields 수정
  be/glossymatcha/migrations/0005_alter_productimages_options_and_more.py
  be/glossymatcha/models.py
Labels: BE_issue, fix

#91 [BE] fix: admin 수정
  be/glossymatcha/admin.py
Labels: BE_issue, fix

#94 [BE] fix: note 필드 제거 및 sub_description 이름 수정
  be/glossymatcha/admin.py
  be/glossymatcha/migrations/0002_remove_products_note_remove_products_note_en_and_more.py
  be/glossymatcha/models.py
Labels: BE_issue, fix

#98 [BE] fix: edit ProductSerializer
  be/glossymatcha/serializers.py
Labels: BE_issue, fix

#99 [BE] fix: edit ProductDetailSerializer, ProductListSerializer
  be/glossymatcha/serializers.py
Labels: BE_issue, fix

#100 [BE] fix: edit WorkRecord logic
  be/glossymatcha/models.py
Labels: feature, BE_issue, fix

#101 [BE] feat: WorkRecord 법정 주휴수당 자동계산 추가
  be/glossymatcha/migrations/0003_workrecord_pay_period_weeks.py
  be/glossymatcha/models.py
Labels: feature, BE_issue, fix

#105 Be/fix/models
  be/glossymatcha/migrations/0004_alter_inquiries_message.py
  be/glossymatcha/models.py
Labels: feature, BE_issue, fix

#107 [BE] fix: 한국어 문의 내용 선택사항 validate 변경
  be/glossymatcha/serializers.py
Labels: BE_issue, fix

#111 [BE] fix: del message_en field & add yearly_sales_costs auto update
  be/glossymatcha/migrations/0005_remove_inquiries_message_en_alter_inquiries_message.py
  be/glossymatcha/migrations/0006_alter_products_description_alter_products_name.py
  be/glossymatcha/models.py
Labels: feature, BE_issue, fix

#112 [BE] fix: del message_en & product ko/en validationerror setup
  be/glossymatcha/serializers.py
Labels: BE_issue, fix

#116 [FE] 헤더 수정
  fe/src/app/inquire/page.tsx
  fe/src/app/page.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Home/ImageSection/ImageSection.tsx
Labels: FE_issue, fix

#118 [FE] 홈 화면 피드백 수정
  fe/src/app/page.tsx
  fe/src/components/Home/SideInfo/SideInfo.module.scss
  fe/src/components/Home/SideInfo/SideInfo.tsx
Labels: FE_issue, fix

#119 [BE] 제품관련(Products)
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: feature, BE_issue

#120 [FE] 홈 화면 video 추가
  fe/public/videos/glossy-intro.mp4
  fe/public/videos/glossy-intro.webm
  fe/src/components/Home/ImageSection/ImageSection.module.scss
  fe/src/components/Home/ImageSection/ImageSection.tsx
Labels: feature, FE_issue

#126 [FE] 문의하기 API 연결
  fe/src/app/inquire/page.tsx
Labels: feature, FE_issue

#127 [FE] feat: 체험형 콘텐츠 함수 구현
  fe/src/utils/matchaRecommendation.ts
Labels: feature, FE_issue

#130 [FE] feat: react-toastify install & useShare 커스텀 훅 구현
  fe/package-lock.json
  fe/package.json
  fe/src/hooks/useShare.ts
Labels: feature, FE_issue

#132 [FE] feat: 체험형 인트로 구현
  fe/src/components/GlossyPick/Intro.tsx
  fe/src/components/GlossyPick/MatchaGenerator.tsx
Labels: feature, FE_issue

#133 [BE] feat: Staff & WorkRecord
  be/glossymatcha/forms.py
  be/glossymatcha/templates/glossymatcha/staff/create.html
  be/glossymatcha/templates/glossymatcha/staff/delete.html
  be/glossymatcha/templates/glossymatcha/staff/detail.html
  be/glossymatcha/templates/glossymatcha/staff/list.html
  be/glossymatcha/templates/glossymatcha/staff/work_record.html
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: feature, BE_issue

#136 [FE] feat: 체험형 결과 컴포넌트 구현
  fe/public/images/glossy-pick/menu/barley-cream.png
  fe/public/images/glossy-pick/menu/green-lemonade.png
  fe/public/images/glossy-pick/menu/jeju-oreum.png
  fe/public/images/glossy-pick/menu/matcha-latte.png
  fe/public/images/glossy-pick/menu/matcha-mojito.png
  fe/public/images/glossy-pick/menu/matcha-spanner.png
  fe/public/images/glossy-pick/menu/matcha-straight.png
  fe/src/components/GlossyPick/MatchaGenerator.module.scss
  fe/src/components/GlossyPick/MatchaGenerator.tsx
  fe/src/components/GlossyPick/ResultSection.module.scss
  fe/src/components/GlossyPick/ResultSection.tsx
  fe/src/data/menuData.ts
Labels: feature, FE_issue

#137 [BE] DailySales
  be/glossymatcha/forms.py
  be/glossymatcha/templates/glossymatcha/daily_sales/create.html
  be/glossymatcha/templates/glossymatcha/daily_sales/delete.html
  be/glossymatcha/templates/glossymatcha/daily_sales/detail.html
  be/glossymatcha/templates/glossymatcha/daily_sales/list.html
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: feature, BE_issue

#140 [BE] Monthly Sales
  be/glossymatcha/forms.py
  be/glossymatcha/templates/glossymatcha/sales/create.html
  be/glossymatcha/templates/glossymatcha/sales/delete.html
  be/glossymatcha/templates/glossymatcha/sales/detail.html
  be/glossymatcha/templates/glossymatcha/sales/list.html
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: feature, BE_issue

#141 [BE] fix: monthly sales Forms 오타 수정
  be/glossymatcha/forms.py
Labels: BE_issue, fix

#143 [BE] YearlySales
  be/glossymatcha/forms.py
  be/glossymatcha/templates/glossymatcha/yearly_sales/create.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/delete.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/detail.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/list.html
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: feature, BE_issue

#144 [FE]요구사항 수정(mainbanner,midbanner)
  fe/src/components/Product/ProductMainBanner.module.scss
  fe/src/components/Product/ProductMidBanner.module.scss
Labels: feature, FE_issue, fix

#145 [BE] Staff edit Error resolve
  be/glossymatcha/migrations/0007_alter_staff_nickname.py
  be/glossymatcha/models.py
  be/glossymatcha/views.py
Labels: BE_issue, fix

#146 [BE] fix: 합계 오류 개선
  be/glossymatcha/templates/glossymatcha/sales/list.html
  be/glossymatcha/views.py
Labels: BE_issue, fix

#150 [BE] fix: 직원 오류 수정
  be/glossymatcha/models.py
  be/glossymatcha/templates/glossymatcha/staff/list.html
Labels: BE_issue, fix

#151 [BE] fix: main 직원 수 수정
  be/glossymatcha/views.py
Labels: BE_issue, fix

#152 [BE] fix: 급여기록 TypeError 수정
  be/glossymatcha/models.py
Labels: BE_issue, fix

#155 [BE] fix: 전화번호는 숫자만 입력 가능하게 수정
  be/glossymatcha/forms.py
Labels: BE_issue, fix

#156 [BE] fix: 퇴사 직원 차감되도록 수정
  be/glossymatcha/templates/glossymatcha/staff/list.html
  be/glossymatcha/views.py
Labels: BE_issue, fix

#157 [FE] fix: 체험형 콘텐츠 ResultSection 수정
  fe/src/components/GlossyPick/ResultSection.module.scss
  fe/src/components/GlossyPick/ResultSection.tsx
Labels: FE_issue, fix

#158 [BE] fix: 해당 년도에 일/월별 매출 없으면 입력 불가능하게 수정
  be/glossymatcha/forms.py
Labels: BE_issue, fix

#160 [BE] fix: 월 최근 매출 현황 → 일 최근 매출 현황
  be/glossymatcha/templates/glossymatcha/dashboard.html
  be/glossymatcha/views.py
Labels: BE_issue, fix

#162 [BE] fix: monthly url 수정
  be/glossymatcha/templates/glossymatcha/sales/create.html
  be/glossymatcha/templates/glossymatcha/sales/list.html
Labels: BE_issue, fix

#168 [BE] fix: suppliers email 눌렀을 때 Gmail로 답장하게 수정
  be/glossymatcha/templates/glossymatcha/suppliers/detail.html
Labels: BE_issue, fix

#169 [FE] fix: useDownload IOS 환경 수정
  fe/package-lock.json
  fe/package.json
  fe/src/hooks/useDownload.ts
Labels: FE_issue, fix

#171 [FE] fix: iOS Safari PDF 다운로드 이슈 해결을 위한 폴백 시스템 구현
  fe/src/hooks/useDownload.ts
Labels: FE_issue, fix

#173 [FE] 헤더 문의하기 아이콘 변경
  fe/public/images/icon/inquire.svg
  fe/src/components/Header/Header.tsx
Labels: FE_issue, fix

#175 [BE] fix: monthly button 수정
  be/glossymatcha/templates/glossymatcha/sales/list.html
Labels: BE_issue, fix

#174 [FE] fix: iOS 이미지 다운로드 수정
  fe/src/hooks/useDownload.ts
Labels: FE_issue, fix

#177 [BE] fix: 연별매출 입력 icon 수정
  be/glossymatcha/templates/glossymatcha/yearly_sales/create.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/detail.html
Labels: BE_issue, fix

#181 [FE] fix: useDownload 훅 수정
  fe/package-lock.json
  fe/package.json
  fe/src/app/page.tsx
  fe/src/hooks/useDownload.ts
  fe/src/types/dom-to-image-more.d.ts
Labels: FE_issue, fix

#180 [BE] fix: 연도 입력 필드를 dropdown menu로 변경
  be/glossymatcha/forms.py
Labels: BE_issue, fix

#183 [BE] feat: Create WorkRecordUpdate
  be/glossymatcha/templates/glossymatcha/staff/detail.html
  be/glossymatcha/templates/glossymatcha/staff/work_record.html
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: feature, BE_issue, fix

#185 [BE] fix: 급여 기록 입력 저장하기 후 출력 페이지 대시보드에서 해당 직원 페이지로 이동하게끔 수정
  be/glossymatcha/views.py
Labels: BE_issue, fix

#186 [BE] fix: 직원 등록 시 닉네임을 선택사항으로 수정
  be/glossymatcha/forms.py
  be/glossymatcha/models.py
  be/glossymatcha/templates/glossymatcha/staff/create.html
  be/glossymatcha/templates/glossymatcha/staff/detail.html
Labels: BE_issue, fix

#187 [BE] fix: 최근 급여 기록 삭제 추가 구현
  be/glossymatcha/templates/glossymatcha/staff/detail.html
  be/glossymatcha/templates/glossymatcha/staff/work_record_delete.html
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: feature, BE_issue, fix

#188 [BE] fix: 직원 근무 형태별로 분류 | 입사일 기준 오름차순 | 퇴사처리 후 맨 아래로 이동
  be/glossymatcha/views.py
Labels: BE_issue, fix

#190 [BE] fix: 퇴사 처리 된 직원은 근무형태가 자동으로 퇴사로 바뀌게 수정
  be/glossymatcha/forms.py
  be/glossymatcha/models.py
  be/glossymatcha/views.py
Labels: BE_issue, fix

#191 [FE] main,mid banner 수정
  fe/src/components/Product/ProductDescription.module.scss
  fe/src/components/Product/ProductDescription.tsx
  fe/src/components/Product/ProductMainBanner.module.scss
  fe/src/components/Product/ProductMainBanner.tsx
  fe/src/components/Product/ProductMidBanner.module.scss
  fe/src/components/Product/ProductMidBanner.tsx
  fe/src/services/productApi.ts
Labels: feature, FE_issue, fix

#193 [BE] fix: 퇴사 처리 시 이전 근무형태도 포함하여 구분 | 퇴사 날짜 삭제 시 원래 근무형태로 자동 변환으로 수정
  be/glossymatcha/forms.py
  be/glossymatcha/migrations/0008_alter_staff_options_staff_original_employee_type_and_more.py
  be/glossymatcha/models.py
  be/glossymatcha/templates/glossymatcha/staff/detail.html
  be/glossymatcha/templates/glossymatcha/staff/list.html
Labels: BE_issue, fix

#197 [BE] fix: 콤마 포맷팅 빠진부분 수정
  be/glossymatcha/templates/glossymatcha/daily_sales/delete.html
  be/glossymatcha/templates/glossymatcha/daily_sales/detail.html
  be/glossymatcha/templates/glossymatcha/daily_sales/list.html
  be/glossymatcha/templates/glossymatcha/dashboard.html
  be/glossymatcha/templates/glossymatcha/sales/delete.html
  be/glossymatcha/templates/glossymatcha/sales/detail.html
  be/glossymatcha/templates/glossymatcha/sales/list.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/create.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/delete.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/detail.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/list.html
Labels: BE_issue, fix

#199 [BE] fix: 월별 매출 매출원가, 식재료 관련 기입 선택사항으로 수정
  be/glossymatcha/forms.py
  be/glossymatcha/templates/glossymatcha/sales/create.html
Labels: BE_issue, fix

#200 [BE] fix: 퇴사일이 정해진 직원 자동 퇴사 처리로 수정
  be/glossymatcha/forms.py
  be/glossymatcha/management/__init__.py
  be/glossymatcha/management/commands/__init__.py
  be/glossymatcha/management/commands/process_resignations.py
  be/glossymatcha/models.py
Labels: BE_issue, fix

#201 [BE] fix: 근무형태별로 나눈 다음 입사일 기준 오름차순 정렬로 수정
  be/glossymatcha/models.py
Labels: BE_issue, fix

#195 [FE] 언어변환 기본 틀
  fe/i18n/request.ts
  fe/messages/en.json
  fe/messages/ko.json
  fe/middleware.ts
  fe/next.config.ts
  fe/src/app/[locale]/about/page.module.scss
  fe/src/app/[locale]/about/page.tsx
  fe/src/app/[locale]/inquire/page.module.scss
  fe/src/app/[locale]/inquire/page.tsx
  fe/src/app/[locale]/layout.tsx
  fe/src/app/[locale]/page.tsx
  fe/src/app/[locale]/products/page.module.scss
  fe/src/app/[locale]/products/page.tsx
  fe/src/app/[locale]/test/page.tsx
  fe/src/app/layout.tsx
  fe/src/app/page.tsx
  fe/src/components/Header/Header.module.scss
  fe/src/components/Header/Header.tsx
  fe/src/components/Header/LanguageButton/LanguageButton.module.scss
  fe/src/components/Header/LanguageButton/LanguageButton.tsx
  fe/src/components/Home/ImageSection/ImageSection.tsx
  fe/src/components/Home/MobileHome/MobileHome.tsx
  fe/src/components/Home/PcHome/PcHome.tsx
  fe/src/components/Home/SideInfo/SideInfo.tsx
Labels: feature, FE_issue

#202 [FE] fix: 브랜드 소개 컴포넌트 리팩토링
  fe/src/components/About/BrandHistory.module.scss
  fe/src/components/About/BrandHistory.tsx
  fe/src/components/About/BrandPhilosophy.tsx
  fe/src/components/About/JejuMatcha.module.scss
  fe/src/components/About/JejuMatcha.tsx
Labels: FE_issue, fix

#203 [BE] fix: 수동으로 퇴사처리했을 때 근무형태도 퇴사처리되게끔 수정
  be/glossymatcha/models.py
Labels: BE_issue, fix

#207 [BE] fix: 해당 연별 매출의 월별 매출이 모두 삭제되면 연별 매출 0원으로 초기화되지 않고 완전히 삭제로 수정
  be/glossymatcha/models.py
Labels: BE_issue, fix

#208 [BE] fix: 중복되는 daily 매출 url 삭제되면서 변경된 url name으로 수정
  be/glossymatcha/templates/glossymatcha/base.html
  be/glossymatcha/templates/glossymatcha/daily_sales/list.html
  be/glossymatcha/templates/glossymatcha/dashboard.html
  be/glossymatcha/templates/glossymatcha/sales/create.html
  be/glossymatcha/templates/glossymatcha/sales/delete.html
  be/glossymatcha/templates/glossymatcha/sales/detail.html
  be/glossymatcha/templates/glossymatcha/sales/list.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/list.html
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: BE_issue, fix

#209 [BE] fix: 일별 매출 눌렀을 때 월별 매출로 이동하는 오류 수정
  be/glossymatcha/templates/glossymatcha/dashboard.html
Labels: BE_issue, fix

#210 [BE] fix: 배포서버에서 전화번호 복사 안되는 오류 수정
  be/glossymatcha/templates/glossymatcha/suppliers/detail.html
Labels: BE_issue, fix

#211 [BE] fix: 전화번호만 복사하게끔 세부수정
  be/glossymatcha/templates/glossymatcha/suppliers/detail.html
Labels: BE_issue, fix

#212 [BE] fix: 거래처 목록의 email도 gmail로 이동하게끔 수정
  be/glossymatcha/templates/glossymatcha/suppliers/list.html
Labels: BE_issue, fix

#213 [FE] feat: 브랜드 소개 페이지 국영문 전환 구현
  fe/messages/en.json
  fe/messages/ko.json
  fe/src/app/[locale]/about/page.tsx
  fe/src/components/About/BrandHistory.tsx
  fe/src/components/About/BrandIntro.tsx
  fe/src/components/About/BrandPhilosophy.tsx
  fe/src/components/About/JejuMatcha.module.scss
  fe/src/components/About/JejuMatcha.tsx
  fe/src/components/Nav/ScrollNav.tsx
Labels: feature, FE_issue

#215 [FE] 모바일 홈 스크롤 수정
  fe/i18n/request.ts
  fe/src/app/[locale]/about/page.tsx
  fe/src/app/[locale]/layout.tsx
  fe/src/app/[locale]/page.tsx
  fe/src/app/page.tsx
  fe/src/components/About/BrandIntro.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Home/ImageSubInfo/ImageSubInfo.tsx
  fe/src/components/Home/MobileHome/MobileHome.module.scss
  fe/src/components/Home/MobileHome/MobileHome.tsx
  fe/src/components/Home/SideInfo/SideInfo.tsx
  fe/src/styles/globals.scss
Labels: feature, FE_issue, fix

#216 [BE] feat: 최근 30일/12개월간의 일/월별 매출 데이터 차트 view 추가
  be/glossymatcha/views.py
Labels: feature, BE_issue

#217 [BE] feat: 전월/전년 대비 매출 비교 분석 및 손익 분석 view 추가
  be/glossymatcha/views.py
Labels: feature, BE_issue

#218 [FE] iOS 홈 영상 속도개선
  fe/public/images/icon/headset.svg
  fe/public/images/icon/inquire.svg
  fe/public/videos/intro-mb.mp4
  fe/public/videos/intro-mb.webm
  fe/src/app/[locale]/page.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Home/MobileHome/MobileHome.tsx
  fe/src/components/Home/SoundButton/SoundButton.tsx
Labels: FE_issue, fix

#220 [BE] feat: 월별 매출 현황 excel file 생성 view 추가
  be/glossymatcha/views.py
Labels: feature, BE_issue

#219 [FE] feat: 체험형 국영문 전환 구현
  fe/messages/en.json
  fe/messages/ko.json
  fe/src/components/GlossyPick/GlossyPickHeader.tsx
  fe/src/components/GlossyPick/Intro.tsx
  fe/src/components/GlossyPick/QuestionSection.tsx
  fe/src/components/GlossyPick/ResultSection.tsx
  fe/src/data/menuData.ts
  fe/src/data/questions.ts
  fe/src/utils/matchaRecommendation.ts
Labels: feature, FE_issue

#221 [BE] feat: 연별 매출 현황 excel file 생성 view 추가
  be/glossymatcha/views.py
Labels: feature, BE_issue

#222 [BE] feat: 월/연별 매출 데이터 엑셀 파일 내보내기 url 추가
  be/glossymatcha/urls.py
Labels: feature, BE_issue

#228 [BE] feat: 월/연별 매출 목록 페이지에서 개별 월/연별 엑셀 파일 내보내기로 templates 수정
  be/glossymatcha/templates/glossymatcha/sales/list.html
  be/glossymatcha/templates/glossymatcha/yearly_sales/list.html
Labels: feature, BE_issue

#231 [BE] feat: 개별 월/연별 매출 엑셀 다운로드 urls 추가
  be/glossymatcha/urls.py
Labels: feature, BE_issue

#230 [FE] fix: useDownload ios 환경 개선
  fe/src/components/GlossyPick/MatchaGenerator.tsx
  fe/src/hooks/useDownload.ts
Labels: FE_issue, fix

#232 [BE] feat: 메인 대시보드에도 올해 매출 표시되게끔 추가
  be/glossymatcha/templates/glossymatcha/dashboard.html
  be/glossymatcha/views.py
Labels: feature, BE_issue

#233 [FE] fix: useDownload iOS 새 탭 열기 방식으로 개선
  fe/src/components/GlossyPick/MatchaGenerator.tsx
  fe/src/hooks/useDownload.ts
Labels: FE_issue, fix

#235 [FE] fix: 브랜드소개, 체험형 heading 구조 정리
  fe/src/components/About/BrandHistory.tsx
  fe/src/components/About/BrandPhilosophy.tsx
  fe/src/components/About/JejuMatcha.tsx
  fe/src/components/GlossyPick/ResultSection.tsx
Labels: FE_issue, fix

#236 feat: api 연결용 임시 파일 생성
  fe/src/components/Product/ProductDescription.module.module.scss
  fe/src/components/Product/ProductDescription.tsx
  fe/src/data/mockProducts.ts
Labels: feature, FE_issue, fix

#237 [FE]feat: https로 수정
  fe/src/components/Product/ProductDescription.module.scss
  fe/src/components/Product/ProductDescription.tsx
  fe/src/services/productApi.ts
Labels: feature, FE_issue, fix

#239 [BE] fix: admin url name 수정
  be/glossy/urls.py
Labels: BE_issue, fix

#241 [FE] feat: 브랜드 소개 페이지 FadeInOut 애니메이션 적용
  fe/src/components/About/BrandHistory.tsx
  fe/src/components/About/BrandIntro.tsx
  fe/src/components/About/BrandPhilosophy.tsx
  fe/src/components/About/JejuMatcha.tsx
  fe/src/components/FadeInUp/FadeInUp.tsx
Labels: feature, FE_issue

#246 [FE] API 연동
  fe/next.config.ts
  fe/src/app/[locale]/products/page.tsx
  fe/src/components/Product/ProductDescription.tsx
  fe/src/components/Product/ProductMidBanner.tsx
  fe/src/data/mockProducts.ts
  fe/src/services/productApi.ts
  fe/src/utils/textFormatter.tsx
Labels: feature, FE_issue, fix

#249 [FE] feat: ios 환경 web share api 추가
  fe/src/hooks/useDownload.ts
Labels: feature, FE_issue

#253 [FE]|| 수정
  fe/src/components/Product/ProductDescription.tsx
Labels: feature, FE_issue, fix

#252 [FE] fix: useDownload 훅 제거
  fe/src/components/GlossyPick/MatchaGenerator.tsx
  fe/src/components/GlossyPick/ResultSection.tsx
  fe/src/hooks/useDownload.ts
Labels: FE_issue, fix

#254 [FE] mock 데이터 수정
  fe/src/components/Product/ProductDescription.tsx
Labels: feature, FE_issue, fix

#257 [FE] PC 홈 화면 수정
  fe/src/components/Home/ImageSection/ImageSection.module.scss
  fe/src/components/Home/ImageSection/ImageSection.tsx
  fe/src/components/Home/ImageSubInfo/ImageSubInfo.module.scss
  fe/src/components/Home/ImageSubInfo/ImageSubInfo.tsx
  fe/src/components/Home/MobileHome/MobileHome.module.scss
  fe/src/components/Home/PcHome/PcHome.module.scss
  fe/src/components/Home/PcHome/PcHome.tsx
  fe/src/components/Home/SideInfo/SideInfo.module.scss
  fe/src/styles/globals.scss
Labels: FE_issue, fix

#258 [FE] - 문제 해결
  fe/src/components/Product/ProductDescription.module.scss
  fe/src/components/Product/ProductDescription.tsx
Labels: feature, FE_issue, fix

#259 [FE] description 오류 수정중
  fe/src/components/Product/ProductDescription.tsx
Labels: feature, FE_issue, fix

#262 [FE]feat: type error 수정
  fe/src/app/[locale]/products/page.tsx
  fe/src/services/productApi.ts
Labels: feature, FE_issue

#265 [FE] mock 수정
  fe/src/app/[locale]/products/page.tsx
  fe/src/components/Product/ProductMidBanner.tsx
  fe/src/services/productApi.ts
Labels: feature, FE_issue, fix, Finish 👍🏻👩🏻‍💻

#266 [FE] 홈 구조 변경 및 언어 번역
  fe/messages/en.json
  fe/messages/ko.json
  fe/public/images/icon/headset.svg
  fe/src/app/[locale]/page.tsx
  fe/src/components/Header/Header.module.scss
  fe/src/components/Header/Header.tsx
  fe/src/components/Home/ImageSection/ImageSection.tsx
  fe/src/components/Home/ImageSubInfo/ImageSubInfo.tsx
  fe/src/components/Home/MobileHome/MobileHome.tsx
  fe/src/components/Home/SideInfo/SideInfo.tsx
Labels: feature, FE_issue

#267 [FE] feat: 코드 정리
  fe/src/app/[locale]/products/page.tsx
  fe/src/components/Product/ProductDescription.tsx
  fe/src/components/Product/ProductMainBanner.tsx
  fe/src/components/Product/ProductMidBanner.tsx
  fe/src/data/mockProducts.ts
  fe/src/services/productApi.ts
  fe/src/utils/textFormatter.tsx
Labels: feature, FE_issue, fix

#268 [FE] feat: 푸터 구현
  fe/public/images/icon/icon-google.png
  fe/public/images/icon/icon-insta.png
  fe/public/images/icon/icon-naver.png
  fe/public/images/logo/logo-w.png
  fe/src/components/Footer/Footer.module.scss
  fe/src/components/Footer/Footer.tsx
Labels: feature, FE_issue

#272 [FE] fix: 브랜드 소개 - 연혁 섹션 애니메이션 수정
  fe/src/components/About/BrandHistory.tsx
Labels: FE_issue, fix

#276 [FE] feat: 브랜드 소개, 체험형 메타 데이터 추가
  fe/public/images/logo/logo-BI.png
  fe/src/app/[locale]/about/page.tsx
  fe/src/app/[locale]/test/page.tsx
  fe/src/app/layout.tsx
Labels: feature, FE_issue

#277 [BE] fix: 대시보드 반응형 개선
  be/glossymatcha/static/glossymatcha/css/style.css
  be/glossymatcha/templates/glossymatcha/dashboard.html
Labels: BE_issue, fix

#279 [FE]feat: mock 파일 정리
  fe/src/data/mockProducts.ts
  fe/src/services/productApi.ts
  fe/src/utils/textFormatter.tsx
Labels: feature, FE_issue, fix

#282 [FE] fix: ScrollNav 메뉴 액티브 오류 수정
  fe/src/components/Nav/ScrollNav.tsx
Labels: FE_issue, fix

#283 [FE]feat: 영문 번역 & 상세 오류 수정 전
  fe/src/app/[locale]/products/page.tsx
  fe/src/components/Product/ProductDescription.tsx
  fe/src/components/Product/ProductMainBanner.tsx
  fe/src/components/Product/ProductMidBanner.tsx
  fe/src/services/productApi.ts
Labels: FE_issue, fix

#285 [FE] PC/Mobile 버전 미디어 쿼리 사용으로 변경
  fe/src/app/[locale]/page.tsx
  fe/src/app/layout.tsx
  fe/src/components/Home/MobileHome/MobileHome.module.scss
  fe/src/components/Home/MobileHome/MobileHome.tsx
  fe/src/components/Home/PcHome/PcHome.module.scss
  fe/src/components/Home/PcHome/PcHome.tsx
  fe/src/styles/globals.scss
Labels: FE_issue, fix

#286 [BE] fix: 의존성 패키지 정리
  requirements.txt
Labels: BE_issue, fix

#288 [FE]feat: *n -> mobile에서만 줄바꿈
  fe/src/components/Product/ProductDescription.module.scss
  fe/src/components/Product/ProductMainBanner.module.scss
  fe/src/components/Product/ProductMainBanner.tsx
  fe/src/components/Product/ProductMidBanner.module.scss
  fe/src/components/Product/ProductMidBanner.tsx
  fe/src/utils/textFormatter.tsx
Labels: feature, FE_issue, fix

#289 [FE] 이미지 변경
  fe/public/images/home/cafe-glossy-matcha-inside.webp
  fe/public/images/home/cafe-glossy-matcha-outside.webp
  fe/public/images/home/glossy-pick.webp
  fe/public/images/home/matcha-test.webp
  fe/src/app/[locale]/page.tsx
  fe/src/components/Header/Header.module.scss
  fe/src/components/Home/MobileHome/MobileHome.module.scss
  fe/src/components/Home/PcHome/PcHome.module.scss
  fe/src/components/Home/SideInfo/SideInfo.module.scss
Labels: FE_issue, fix

#290 [FE] fix: 브랜드 소개 페이지 수정
  fe/messages/en.json
  fe/public/images/glossy-pick/intro.JPG
  fe/public/images/glossy-pick/intro.webp
  fe/src/components/About/BrandHistory.module.scss
  fe/src/components/About/BrandHistory.tsx
  fe/src/components/GlossyPick/Intro.tsx
  fe/src/components/Nav/ScrollNav.tsx
Labels: feature, FE_issue, fix

#291 [FE] 경로명 test -> glossypick
  fe/messages/en.json
  fe/messages/ko.json
  fe/src/app/[locale]/glossypick/page.tsx
  fe/src/app/[locale]/page.tsx
  fe/src/components/Header/Header.tsx
Labels: FE_issue, fix

#292 [FE]feat: api 주소 수정
  fe/next.config.ts
  fe/src/app/[locale]/products/page.module.scss
  fe/src/services/productApi.ts
Labels: FE_issue, fix

#293 [FE] fix: footer css 수정
  fe/src/components/Footer/Footer.module.scss
Labels: FE_issue, fix

#295 [BE] feat: Create Test Code
  be/glossymatcha/tests.py
Labels: feature, BE_issue

#297 [FE] feat: 푸터 스토어 추가 & JSDoc 추가
  fe/public/images/icon/icon-store.png
  fe/src/components/Footer/Footer.tsx
  fe/src/hooks/useShare.ts
Labels: feature, FE_issue

#299 [BE] feat: Create dailypw model
  be/glossymatcha/migrations/0009_dailypassword_alter_staff_options.py
  be/glossymatcha/models.py
Labels: feature, BE_issue

#302 [BE] feat: Create dailypw view
  be/glossymatcha/views.py
Labels: feature, BE_issue

#303 [BE] feat: Create dailypw middleware
  be/glossymatcha/middleware.py
Labels: feature, BE_issue

#307 [BE] feat: Create dailypw form 수정
  be/glossymatcha/forms.py
Labels: BE_issue, fix

#308 [BE] feat: Create dailypw templates
  be/glossymatcha/templates/glossymatcha/daily_password_check.html
Labels: feature, BE_issue

#309 [BE] feat: 일별 비밀번호 templates 생성
  be/glossymatcha/templates/glossymatcha/daily_password/create.html
  be/glossymatcha/templates/glossymatcha/daily_password/list.html
  be/glossymatcha/templates/glossymatcha/daily_password_check.html
Labels: feature, BE_issue

#312 [BE] fix: 로그인 순서 변경
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: BE_issue, fix

#315 [BE] fix: 로그인 유효성 검증 수정
  be/glossymatcha/forms.py
Labels: BE_issue, fix

#316 [BE] fix: CSRF token from POST incorrect 오류 해결
  be/glossymatcha/views.py
Labels: BE_issue, fix

#317 [FE] 스타일 수치 수정
  fe/src/components/Header/Header.module.scss
  fe/src/components/Inquire/InquirePage.module.scss
Labels: FE_issue, fix

#318 [FE] fix: 컴포넌트 margin 수정
  fe/src/components/About/BrandHistory.module.scss
  fe/src/components/Footer/Footer.module.scss
Labels: FE_issue, fix

#320 [BE] fix: csrf 오류 수정
  be/glossymatcha/admin.py
  be/glossymatcha/models.py
  be/glossymatcha/templates/glossymatcha/daily_password_check.html
Labels: BE_issue, fix

#321 [FE] fix: ScrollNav 액티브 오류 수정
  fe/src/components/About/BrandHistory.module.scss
  fe/src/components/Nav/ScrollNav.tsx
Labels: FE_issue, fix

#325 [FE]feat: 상세 버튼 수정
  fe/src/app/[locale]/products/page.tsx
  fe/src/components/Product/ProductDescription.module.scss
  fe/src/components/Product/ProductDescription.tsx
  fe/src/components/Product/ProductDetails.module.scss
  fe/src/components/Product/ProductDetails.tsx
  fe/src/components/Product/ProductStore.module.scss
Labels: FE_issue, fix

#328 [FE] 헤더 포커스 경고 수정
  fe/src/components/Header/Header.tsx
Labels: FE_issue, fix

#330 README.md Update
  README.md
Labels: documentation

#339 [FE]중복 코드 정리
  fe/src/app/[locale]/products/page.module.scss
  fe/src/app/[locale]/products/page.tsx
  fe/src/components/Product/ProductDescription.tsx
  fe/src/components/Product/ProductDetails.tsx
  fe/src/components/Product/ProductMainBanner.tsx
  fe/src/components/Product/ProductMidBanner.tsx
  fe/src/components/Product/ProductStore.tsx
  fe/src/services/productApi.ts
  fe/src/utils/localeUtils.ts
  fe/src/utils/textFormatter.tsx
Labels: FE_issue, fix
