Repository Gloss-y/Glossy_Matcha, pull requests merged in 2025-07, with the labels that each got.

#12 [BE] docs: DRF Project Flow Architecture 추가
  docs/architecture/system-overview.md
Labels: documentation, BE_issue

#13 [BE] docs: DRF Project Flow Architecture 수정
  docs/architecture/system-overview.md
Labels: documentation, BE_issue, fix

#16 [BE] feat: django package install
  requirements.txt
Labels: enhancement, BE_issue

#18 [BE] Create app
  be/accounts/__init__.py
  be/accounts/admin.py
  be/accounts/apps.py
  be/accounts/migrations/__init__.py
  be/accounts/models.py
  be/accounts/tests.py
  be/accounts/urls.py
  be/accounts/views.py
  be/glossymatcha/__init__.py
  be/glossymatcha/admin.py
  be/glossymatcha/apps.py
  be/glossymatcha/migrations/__init__.py
  be/glossymatcha/models.py
  be/glossymatcha/tests.py
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: enhancement, BE_issue

#22 [BE] feat: django package install
  requirements.txt
Labels: documentation, BE_issue

#24 [BE] AWS Package install
  requirements.txt
Labels: BE_issue, fix

#29 feat: push 후 재배포 테스트
  fe/src/app/page.tsx
Labels: FE_issue

#30 [BE] fix: ALLOWED_HOSTS 배포용 설정
  be/glossy/settings.py
Labels: BE_issue, fix

#31 [BE] deploy: 배포 test
  .github/workflows/be-ci.yml
Labels: BE_issue

#32 [ALL] docs: add 7/29_Tue TODO
  docs/TODO.md
Labels: documentation, BE_issue, FE_issue, TODO

#35 [BE] deploy: edit code
  .github/workflows/be-ci.yml
Labels: BE_issue, fix

#45 [BE] Django ORM 구현 및 문의하기 API 구현(DB저장용)
  be/glossy/settings.py
  be/glossymatcha/admin.py
  be/glossymatcha/migrations/0001_initial.py
  be/glossymatcha/migrations/0002_remove_products_is_active_remove_products_is_export_and_more.py
  be/glossymatcha/models.py
  be/glossymatcha/serializers.py
  be/glossymatcha/urls.py
  be/glossymatcha/views.py
Labels: enhancement, BE_issue

#46 [BE] feat: db.sqlite에서 PostgreSQL DB로 교체
  be/glossy/settings.py
Labels: enhancement, BE_issue
